spring.application.name=employee_service
server.port=8089
#spring.datasource.username=root
#spring.datasource.url=jdbc:mysql://localhost:3306/hello
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.password=s87WTG&@$i$dCDBF

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/mydb?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}


spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.security.user.name=user
spring.security.user.password=pass


#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

custom.message=${CUSTOM_MESSAGE}


logging.level.org.springframework.security=ERROR

